/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WritingIndexRouteImport } from './routes/writing/index'
import { Route as WorkIndexRouteImport } from './routes/work/index'
import { Route as VxtIndexRouteImport } from './routes/vxt/index'
import { Route as VxIndexRouteImport } from './routes/vx/index'
import { Route as SupportIndexRouteImport } from './routes/support/index'
import { Route as PartnersIndexRouteImport } from './routes/partners/index'
import { Route as NewsIndexRouteImport } from './routes/news/index'
import { Route as CollaborateIndexRouteImport } from './routes/collaborate/index'
import { Route as AboutIndexRouteImport } from './routes/about/index'
import { Route as WritingSlugRouteImport } from './routes/writing/$slug'
import { Route as SitemapXmlRouteImport } from './routes/sitemap.xml'
import { Route as RobotsTxtRouteImport } from './routes/robots.txt'
import { Route as NewsSlugRouteImport } from './routes/news/$slug'
import { Route as VxtVersionIndexRouteImport } from './routes/vxt/$version/index'
import { Route as VxVersionIndexRouteImport } from './routes/vx/$version/index'
import { Route as VxtVersionDocsIndexRouteImport } from './routes/vxt/$version/docs/index'
import { Route as VxVersionDocsIndexRouteImport } from './routes/vx/$version/docs/index'
import { Route as VxtVersionDocsSplatRouteImport } from './routes/vxt/$version/docs/$'
import { Route as VxVersionDocsSplatRouteImport } from './routes/vx/$version/docs/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WritingIndexRoute = WritingIndexRouteImport.update({
  id: '/writing/',
  path: '/writing/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkIndexRoute = WorkIndexRouteImport.update({
  id: '/work/',
  path: '/work/',
  getParentRoute: () => rootRouteImport,
} as any)
const VxtIndexRoute = VxtIndexRouteImport.update({
  id: '/vxt/',
  path: '/vxt/',
  getParentRoute: () => rootRouteImport,
} as any)
const VxIndexRoute = VxIndexRouteImport.update({
  id: '/vx/',
  path: '/vx/',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportIndexRoute = SupportIndexRouteImport.update({
  id: '/support/',
  path: '/support/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersIndexRoute = PartnersIndexRouteImport.update({
  id: '/partners/',
  path: '/partners/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollaborateIndexRoute = CollaborateIndexRouteImport.update({
  id: '/collaborate/',
  path: '/collaborate/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const WritingSlugRoute = WritingSlugRouteImport.update({
  id: '/writing/$slug',
  path: '/writing/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapXmlRoute = SitemapXmlRouteImport.update({
  id: '/sitemap/xml',
  path: '/sitemap/xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsTxtRoute = RobotsTxtRouteImport.update({
  id: '/robots/txt',
  path: '/robots/txt',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/news/$slug',
  path: '/news/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const VxtVersionIndexRoute = VxtVersionIndexRouteImport.update({
  id: '/vxt/$version/',
  path: '/vxt/$version/',
  getParentRoute: () => rootRouteImport,
} as any)
const VxVersionIndexRoute = VxVersionIndexRouteImport.update({
  id: '/vx/$version/',
  path: '/vx/$version/',
  getParentRoute: () => rootRouteImport,
} as any)
const VxtVersionDocsIndexRoute = VxtVersionDocsIndexRouteImport.update({
  id: '/vxt/$version/docs/',
  path: '/vxt/$version/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const VxVersionDocsIndexRoute = VxVersionDocsIndexRouteImport.update({
  id: '/vx/$version/docs/',
  path: '/vx/$version/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const VxtVersionDocsSplatRoute = VxtVersionDocsSplatRouteImport.update({
  id: '/vxt/$version/docs/$',
  path: '/vxt/$version/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const VxVersionDocsSplatRoute = VxVersionDocsSplatRouteImport.update({
  id: '/vx/$version/docs/$',
  path: '/vx/$version/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/news/$slug': typeof NewsSlugRoute
  '/robots/txt': typeof RobotsTxtRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/writing/$slug': typeof WritingSlugRoute
  '/about/': typeof AboutIndexRoute
  '/collaborate/': typeof CollaborateIndexRoute
  '/news/': typeof NewsIndexRoute
  '/partners/': typeof PartnersIndexRoute
  '/support/': typeof SupportIndexRoute
  '/vx/': typeof VxIndexRoute
  '/vxt/': typeof VxtIndexRoute
  '/work/': typeof WorkIndexRoute
  '/writing/': typeof WritingIndexRoute
  '/vx/$version/': typeof VxVersionIndexRoute
  '/vxt/$version/': typeof VxtVersionIndexRoute
  '/vx/$version/docs/$': typeof VxVersionDocsSplatRoute
  '/vxt/$version/docs/$': typeof VxtVersionDocsSplatRoute
  '/vx/$version/docs/': typeof VxVersionDocsIndexRoute
  '/vxt/$version/docs/': typeof VxtVersionDocsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/news/$slug': typeof NewsSlugRoute
  '/robots/txt': typeof RobotsTxtRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/writing/$slug': typeof WritingSlugRoute
  '/about': typeof AboutIndexRoute
  '/collaborate': typeof CollaborateIndexRoute
  '/news': typeof NewsIndexRoute
  '/partners': typeof PartnersIndexRoute
  '/support': typeof SupportIndexRoute
  '/vx': typeof VxIndexRoute
  '/vxt': typeof VxtIndexRoute
  '/work': typeof WorkIndexRoute
  '/writing': typeof WritingIndexRoute
  '/vx/$version': typeof VxVersionIndexRoute
  '/vxt/$version': typeof VxtVersionIndexRoute
  '/vx/$version/docs/$': typeof VxVersionDocsSplatRoute
  '/vxt/$version/docs/$': typeof VxtVersionDocsSplatRoute
  '/vx/$version/docs': typeof VxVersionDocsIndexRoute
  '/vxt/$version/docs': typeof VxtVersionDocsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/news/$slug': typeof NewsSlugRoute
  '/robots/txt': typeof RobotsTxtRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/writing/$slug': typeof WritingSlugRoute
  '/about/': typeof AboutIndexRoute
  '/collaborate/': typeof CollaborateIndexRoute
  '/news/': typeof NewsIndexRoute
  '/partners/': typeof PartnersIndexRoute
  '/support/': typeof SupportIndexRoute
  '/vx/': typeof VxIndexRoute
  '/vxt/': typeof VxtIndexRoute
  '/work/': typeof WorkIndexRoute
  '/writing/': typeof WritingIndexRoute
  '/vx/$version/': typeof VxVersionIndexRoute
  '/vxt/$version/': typeof VxtVersionIndexRoute
  '/vx/$version/docs/$': typeof VxVersionDocsSplatRoute
  '/vxt/$version/docs/$': typeof VxtVersionDocsSplatRoute
  '/vx/$version/docs/': typeof VxVersionDocsIndexRoute
  '/vxt/$version/docs/': typeof VxtVersionDocsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/news/$slug'
    | '/robots/txt'
    | '/sitemap/xml'
    | '/writing/$slug'
    | '/about/'
    | '/collaborate/'
    | '/news/'
    | '/partners/'
    | '/support/'
    | '/vx/'
    | '/vxt/'
    | '/work/'
    | '/writing/'
    | '/vx/$version/'
    | '/vxt/$version/'
    | '/vx/$version/docs/$'
    | '/vxt/$version/docs/$'
    | '/vx/$version/docs/'
    | '/vxt/$version/docs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/news/$slug'
    | '/robots/txt'
    | '/sitemap/xml'
    | '/writing/$slug'
    | '/about'
    | '/collaborate'
    | '/news'
    | '/partners'
    | '/support'
    | '/vx'
    | '/vxt'
    | '/work'
    | '/writing'
    | '/vx/$version'
    | '/vxt/$version'
    | '/vx/$version/docs/$'
    | '/vxt/$version/docs/$'
    | '/vx/$version/docs'
    | '/vxt/$version/docs'
  id:
    | '__root__'
    | '/'
    | '/news/$slug'
    | '/robots/txt'
    | '/sitemap/xml'
    | '/writing/$slug'
    | '/about/'
    | '/collaborate/'
    | '/news/'
    | '/partners/'
    | '/support/'
    | '/vx/'
    | '/vxt/'
    | '/work/'
    | '/writing/'
    | '/vx/$version/'
    | '/vxt/$version/'
    | '/vx/$version/docs/$'
    | '/vxt/$version/docs/$'
    | '/vx/$version/docs/'
    | '/vxt/$version/docs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NewsSlugRoute: typeof NewsSlugRoute
  RobotsTxtRoute: typeof RobotsTxtRoute
  SitemapXmlRoute: typeof SitemapXmlRoute
  WritingSlugRoute: typeof WritingSlugRoute
  AboutIndexRoute: typeof AboutIndexRoute
  CollaborateIndexRoute: typeof CollaborateIndexRoute
  NewsIndexRoute: typeof NewsIndexRoute
  PartnersIndexRoute: typeof PartnersIndexRoute
  SupportIndexRoute: typeof SupportIndexRoute
  VxIndexRoute: typeof VxIndexRoute
  VxtIndexRoute: typeof VxtIndexRoute
  WorkIndexRoute: typeof WorkIndexRoute
  WritingIndexRoute: typeof WritingIndexRoute
  VxVersionIndexRoute: typeof VxVersionIndexRoute
  VxtVersionIndexRoute: typeof VxtVersionIndexRoute
  VxVersionDocsSplatRoute: typeof VxVersionDocsSplatRoute
  VxtVersionDocsSplatRoute: typeof VxtVersionDocsSplatRoute
  VxVersionDocsIndexRoute: typeof VxVersionDocsIndexRoute
  VxtVersionDocsIndexRoute: typeof VxtVersionDocsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writing/': {
      id: '/writing/'
      path: '/writing'
      fullPath: '/writing/'
      preLoaderRoute: typeof WritingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/': {
      id: '/work/'
      path: '/work'
      fullPath: '/work/'
      preLoaderRoute: typeof WorkIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vxt/': {
      id: '/vxt/'
      path: '/vxt'
      fullPath: '/vxt/'
      preLoaderRoute: typeof VxtIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vx/': {
      id: '/vx/'
      path: '/vx'
      fullPath: '/vx/'
      preLoaderRoute: typeof VxIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support/': {
      id: '/support/'
      path: '/support'
      fullPath: '/support/'
      preLoaderRoute: typeof SupportIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners/': {
      id: '/partners/'
      path: '/partners'
      fullPath: '/partners/'
      preLoaderRoute: typeof PartnersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/': {
      id: '/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collaborate/': {
      id: '/collaborate/'
      path: '/collaborate'
      fullPath: '/collaborate/'
      preLoaderRoute: typeof CollaborateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writing/$slug': {
      id: '/writing/$slug'
      path: '/writing/$slug'
      fullPath: '/writing/$slug'
      preLoaderRoute: typeof WritingSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap/xml': {
      id: '/sitemap/xml'
      path: '/sitemap/xml'
      fullPath: '/sitemap/xml'
      preLoaderRoute: typeof SitemapXmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots/txt': {
      id: '/robots/txt'
      path: '/robots/txt'
      fullPath: '/robots/txt'
      preLoaderRoute: typeof RobotsTxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/news/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vxt/$version/': {
      id: '/vxt/$version/'
      path: '/vxt/$version'
      fullPath: '/vxt/$version/'
      preLoaderRoute: typeof VxtVersionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vx/$version/': {
      id: '/vx/$version/'
      path: '/vx/$version'
      fullPath: '/vx/$version/'
      preLoaderRoute: typeof VxVersionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vxt/$version/docs/': {
      id: '/vxt/$version/docs/'
      path: '/vxt/$version/docs'
      fullPath: '/vxt/$version/docs/'
      preLoaderRoute: typeof VxtVersionDocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vx/$version/docs/': {
      id: '/vx/$version/docs/'
      path: '/vx/$version/docs'
      fullPath: '/vx/$version/docs/'
      preLoaderRoute: typeof VxVersionDocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vxt/$version/docs/$': {
      id: '/vxt/$version/docs/$'
      path: '/vxt/$version/docs/$'
      fullPath: '/vxt/$version/docs/$'
      preLoaderRoute: typeof VxtVersionDocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vx/$version/docs/$': {
      id: '/vx/$version/docs/$'
      path: '/vx/$version/docs/$'
      fullPath: '/vx/$version/docs/$'
      preLoaderRoute: typeof VxVersionDocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NewsSlugRoute: NewsSlugRoute,
  RobotsTxtRoute: RobotsTxtRoute,
  SitemapXmlRoute: SitemapXmlRoute,
  WritingSlugRoute: WritingSlugRoute,
  AboutIndexRoute: AboutIndexRoute,
  CollaborateIndexRoute: CollaborateIndexRoute,
  NewsIndexRoute: NewsIndexRoute,
  PartnersIndexRoute: PartnersIndexRoute,
  SupportIndexRoute: SupportIndexRoute,
  VxIndexRoute: VxIndexRoute,
  VxtIndexRoute: VxtIndexRoute,
  WorkIndexRoute: WorkIndexRoute,
  WritingIndexRoute: WritingIndexRoute,
  VxVersionIndexRoute: VxVersionIndexRoute,
  VxtVersionIndexRoute: VxtVersionIndexRoute,
  VxVersionDocsSplatRoute: VxVersionDocsSplatRoute,
  VxtVersionDocsSplatRoute: VxtVersionDocsSplatRoute,
  VxVersionDocsIndexRoute: VxVersionDocsIndexRoute,
  VxtVersionDocsIndexRoute: VxtVersionDocsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
